update pipeline script

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -15,3 +15,10 @@ backend-test:
   stage: backend-test
   script:
     - echo "Testing"
+    - amplify mock function usersLambda --event src/event.json --timeout 20 > outputs.txt
+    - awk '/{/,/} /' outputs.txt | tail -n +4 | head -n -1 > outputs.json
+    - status_code=$(jq -r '.statusCode' outputs.json)
+    - if [[ "$status_code">=200 && "$status_code"<300 ]]; then
+        echo "Status failed";
+        exit 1; # Fail the pipeline
+      fi
